version: "3.6"
services:
  {backdropdb}:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: {backdropdb}
      MYSQL_USER: {dbUser}
      MYSQL_PASSWORD: {dbPassword}
      MYSQL_ROOT_PASSWORD: root
    expose:
        - "3306"
    volumes:
    - {backdropdb}:/var/lib/mysql
  
  web:
    build: .
    ports:
     - {portNumber}:80
    volumes:
    - ./files:/app/files
    - ./layouts:/app/layouts
    - ./modules:/app/modules
    - ./sites:/app/sites
    - ./themes:/app/themes

volumes:
  {backdropdb}:
